//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZero.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbLocalEntities : DbContext
    {
        public dbLocalEntities()
            : base("name=dbLocalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Peripherals> Peripherals { get; set; }
        public virtual DbSet<PeripheralShelf> PeripheralShelf { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Rack> Rack { get; set; }
        public virtual DbSet<Rule> Rule { get; set; }
        public virtual DbSet<Shelves> Shelves { get; set; }
        public virtual DbSet<SignIn> SignIn { get; set; }
        public virtual DbSet<SpareParts> SpareParts { get; set; }
        public virtual DbSet<SparePartsShelves> SparePartsShelves { get; set; }
        public virtual DbSet<SubtypeWarehouseType> SubtypeWarehouseType { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeHall> TypeHall { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WarehouseType> WarehouseType { get; set; }
    }
}
