//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZero.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeripheralShelf
    {
        public int ID { get; set; }
        public int PeripheralID { get; set; }
        public int ShelfID { get; set; }
    
        public virtual Peripherals Peripherals { get; set; }
        public virtual Shelves Shelves { get; set; }
    }
}
