//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZero.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartsShelves
    {
        public int ID { get; set; }
        public int IDSpareParts { get; set; }
        public int IDShelf { get; set; }
    
        public virtual Shelves Shelves { get; set; }
        public virtual SpareParts SpareParts { get; set; }

       
    }
}
