//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppZero.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SparePartsShelves
    {
        public int ID { get; set; }
        public int IDSpareParts { get; set; }
        public int IDShelf { get; set; }
    
        public virtual Shelves Shelves { get; set; }
        public virtual SpareParts SpareParts { get; set; }
    }
}
